export const SET_CONFIRM_FORGOT_PASSWORD_USERNAME = 'SET_CONFIRM_FORGOT_PASSWORD_USERNAME';
export const SET_CONFIRM_FORGOT_PASSWORD_CODE = 'SET_CONFIRM_FORGOT_PASSWORD_CODE';
export const SET_CONFIRM_FORGOT_PASSWORD_PASSWORD = 'SET_CONFIRM_FORGOT_PASSWORD_PASSWORD';
export const ATTEMPT_CONFIRM_FORGOT_PASSWORD = 'ATTEMPT_CONFIRM_FORGOT_PASSWORD';
export const CONFIRM_FORGOT_PASSWORD_SUCCESS = 'CONFIRM_FORGOT_PASSWORD_SUCCESS';
export const CONFIRM_FORGOT_PASSWORD_FAIL = 'CONFIRM_FORGOT_PASSWORD_FAIL';
export const CONFIRM_FORGOT_PASSWORD_RESET_STATE = 'CONFIRM_FORGOT_PASSWORD_RESET_STATE';
