export const SET_CONFIRM_USERNAME = 'SET_CONFIRM_USERNAME';
export const SET_CONFIRM_CODE = 'SET_CONFIRM_CODE';
export const ATTEMPT_CONFIRM = 'ATTEMPT_CONFIRM';
export const CONFIRM_SUCCESS = 'CONFIRM_SUCCESS';
export const CONFIRM_FAIL = 'CONFIRM_FAIL';
export const CONFIRM_RESET_STATE = 'CONFIRM_RESET_STATE';
