export const SET_FORGOT_USERNAME = 'SET_FORGOT_USERNAME';
export const ATTEMPT_FORGOT = 'ATTEMPT_FORGOT';
export const FORGOT_SUCCESS = 'FORGOT_SUCCESS';
export const FORGOT_FAIL = 'FORGOT_FAIL';
export const FORGOT_RESET_STATE = 'FORGOT_RESET_STATE';
