export const SET_RESEND_USERNAME = 'SET_RESEND_USERNAME';
export const ATTEMPT_RESEND = 'ATTEMPT_RESEND';
export const RESEND_SUCCESS = 'RESEND_SUCCESS';
export const RESEND_FAIL = 'RESEND_FAIL';
export const RESEND_RESET_STATE = 'RESEND_RESET_STATE';
