export const SET_SIGNUP_USERNAME = 'SET_SIGNUP_USERNAME';
export const SET_SIGNUP_EMAIL = 'SET_SIGNUP_EMAIL';
export const SET_SIGNUP_PASSWORD = 'SET_SIGNUP_PASSWORD';
export const ATTEMPT_SIGNUP = 'ATTEMPT_SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const SIGNUP_RESET_STATE = 'SIGNUP_RESET_STATE';
