import AppTheme from '../../../../../Themes';

const Styles = {
  form: {
    display: 'flex',
    flexDirection: 'column',
    width: '30%',
    maxWidth: '450px',
    minWidth: '300px',
    alignItems: 'center',
  },
  inputField: {
    width: '100%',
    color: AppTheme.white,
    backgroundColor: 'transparent',
    border: 'none',
    borderBottomStyle: 'solid',
    borderBottomWidth: '1px',
    borderBottomColor: AppTheme.white,
    fontSize: AppTheme.largeFont,
    outline: 'none',
    marginTop: '30px',
  },
  submitButtonValid: {
    width: '100%',
    height: '40px',
    backgroundColor: AppTheme.white,
    color: AppTheme.pink,
    border: 'none',
    borderRadius: '5px',
    borderWidth: '0px',
    marginTop: '10px',
    fontSize: AppTheme.mediumFont,
    textTransform: 'uppercase',
    outline: 'none',
    cursor: 'pointer',
  },
  submitButtonInValid: {
    width: '100%',
    height: '40px',
    backgroundColor: AppTheme.pink,
    color: AppTheme.white,
    border: 'none',
    borderRadius: '5px',
    marginTop: '10px',
    fontSize: AppTheme.mediumFont,
    textTransform: 'uppercase',
    outline: 'none',
    borderWidth: '1px',
    borderColor: AppTheme.white,
    borderStyle: 'solid',
    cursor: 'pointer',
  },
  loadingContainer: {
    backgroundColor: AppTheme.white,
    height: '40px',
    width: '100%',
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'center',
    border: 'none',
    borderRadius: '5px',
    marginTop: '10px',
  },
  errorContainer: {
    width: '100%',
    fontSize: AppTheme.smallFont,
    marginTop: '10px',
    height: '40px',
  },
  description: {
    width: '100%',
    marginTop: '10px',
    fontSize: AppTheme.smallFont,
  },
  buttonContainer: {
    display: 'flex',
    flex: 1,
    width: '100%',
    justifyContent: 'space-between',
  },
  loginButton: {
    border: 'none',
    backgroundColor: AppTheme.pink,
    height: '25px',
    width: '50%',
    marginTop: '10px',
    textAlign: 'left',
    padding: '0px',
    color: AppTheme.white,
    outline: 'none',
    cursor: 'pointer',
  },
  signupButton: {
    border: 'none',
    backgroundColor: AppTheme.pink,
    height: '25px',
    width: '50%',
    marginTop: '10px',
    textAlign: 'right',
    padding: '0px',
    color: AppTheme.white,
    outline: 'none',
    cursor: 'pointer',
  },
};

export default Styles;
