import AppTheme from '../../Themes';

const Styles = {
  container: {
    display: 'flex',
    flex: 1,
    backgroundColor: AppTheme.pink,
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    color: AppTheme.white,
    fontWeight: 'bold',
    fontSize: AppTheme.largeFont,
  },
  content: {
    display: 'flex',
    flexDirection: 'column',
    width: '30%',
    maxWidth: '450px',
    minWidth: '300px',
    alignItems: 'center',
  },
  button: {
    display: 'flex',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    height: '40px',
    backgroundColor: AppTheme.white,
    color: AppTheme.pink,
    fontSize: AppTheme.mediumFont,
    border: 'none',
    borderRadius: '5px',
    fontWeight: 'bold',
    margin: '10px',
    outline: 'none',
  },
  loginButton: {
    display: 'flex',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    height: '40px',
    backgroundColor: AppTheme.pink,
    color: AppTheme.white,
    fontSize: AppTheme.mediumFont,
    border: 'none',
    borderRadius: '5px',
    fontWeight: 'bold',
    margin: '10px',
    borderWidth: '1px',
    borderColor: AppTheme.white,
    borderStyle: 'solid',
    outline: 'none',
  },
};

export default Styles;
