export const SET_LOGIN_USERNAME = 'SET_LOGIN_USERNAME';
export const SET_LOGIN_PASSWORD = 'SET_LOGIN_PASSWORD';
export const ATTEMPT_LOGIN = 'ATTEMPT_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_RESET_STATE = 'LOGIN_RESET_STATE';

export const SET_SIGNUP_USERNAME = 'SET_SIGNUP_USERNAME';
export const SET_SIGNUP_EMAIL = 'SET_SIGNUP_EMAIL';
export const SET_SIGNUP_PASSWORD = 'SET_SIGNUP_PASSWORD';
export const ATTEMPT_SIGNUP = 'ATTEMPT_SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const SIGNUP_RESET_STATE = 'SIGNUP_RESET_STATE';

export const SET_CONFIRM_USERNAME = 'SET_CONFIRM_USERNAME';
export const SET_CONFIRM_CODE = 'SET_CONFIRM_CODE';
export const ATTEMPT_CONFIRM = 'ATTEMPT_CONFIRM';
export const CONFIRM_SUCCESS = 'CONFIRM_SUCCESS';
export const CONFIRM_FAIL = 'CONFIRM_FAIL';
export const CONFIRM_RESET_STATE = 'CONFIRM_RESET_STATE';

export const SET_RESEND_USERNAME = 'SET_RESEND_USERNAME';
export const ATTEMPT_RESEND = 'ATTEMPT_RESEND';
export const RESEND_SUCCESS = 'RESEND_SUCCESS';
export const RESEND_FAIL = 'RESEND_FAIL';
export const RESEND_RESET_STATE = 'RESEND_RESET_STATE';

export const SET_FORGOT_USERNAME = 'SET_FORGOT_USERNAME';
export const ATTEMPT_FORGOT = 'ATTEMPT_FORGOT';
export const FORGOT_SUCCESS = 'FORGOT_SUCCESS';
export const FORGOT_FAIL = 'FORGOT_FAIL';
export const FORGOT_RESET_STATE = 'FORGOT_RESET_STATE';

export default {};
